#!/bin/bash

# vérification du contexte général
verifier()
{
  if [ ! "$1" "$2" ] ; then
    echo "Erreur! $2 n'existe pas"
    exit 1
  fi
}

# Récupération du Makefile
origine="/users/info/pub/s4/M4102C/data/Makefile"
verifier -f "$origine"

for rep in *
do
  if [ -d "$rep" ] ; then
    ln -si "$origine" "$rep"
  fi
done

# liens spécifiques à ce tp04
origine="../../tp03/carrefour"
destination="carrefour"
verifier -d "$destination"
(
cd "$destination"
verifier -d "$origine"
ln -si "$origine"/Auto.* .
ln -si "$origine"/Commutation.* .
ln -si "$origine"/carrefour_main.cpp .
)

origine="../../tp03/prod-cons"
destination="prod-cons"
verifier -d "$destination"
(
cd "$destination"
verifier -d "$origine"
ln -si "$origine"/Consommateur.* .
ln -si "$origine"/EcranManchots.* .
ln -si "$origine"/Element.* .
ln -si "$origine"/Producteur.* .
)
